apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-injector-settings
spec:
  forms:
    - group: basic
      label: 通用注入
      formSchema:
        - $formkit: repeater
          name: rules
          id: rules
          key: rules
          label: 注入规则
          value: [ ]
          children:
            - $formkit: code
              name: code
              label: 代码
              value: ""
              language: html
              height: 150px
              validation: required
            - $formkit: repeater
              name: pathPatterns
              label: 路径匹配
              value: [ ]
              validation: required
              help: 可以添加多个页面路径. 每个路径的符合 Ant-style 的表达式, 如 /archives/**, 被匹配的页面将会被注入代码
              children:
                - $formkit: text
                  name: pathPattern
                  label: 路径模式
                  value: ""
                  validation: required
            - $formkit: select
              name: location
              label: 注入位置
              value: "footer"
              options:
                - label: "footer"
                  value: "footer"
                - label: "head"
                  value: "head"
                - label: "id"
                  value: "id"
                - label: "selector"
                  value: "selector"
            - $formkit: text
              if: "$value.location === 'id'"
              name: id
              value: ''
              label: 元素 id
              help: 插入到指定 id 的元素中 (尚未完善)
            - $formkit: text
              if: "$value.location === 'selector'"
              name: selector
              value: ''
              label: 选择器
              help: 插入到 CSS selector 匹配到的元素中 (尚未完善)